version: '3'

services:
  statlerwaldorfcorp.teamservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  statlerwaldorfcorp.locationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

